import "@/src/globals.css"
import type { Metadata } from "next"
import { getServerSession } from "next-auth/next"
import { Inter } from "next/font/google"

import { authOptions } from "@/app/api/auth/[...nextauth]/route"
import ToastProvider from "@/providers/toast-provider"
import ClientProvider from "@/providers/client-provider"
import Nav from "@/components/Header/Nav"
import Footer from "@/components/Footer"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Instagram",
  description: "Generated by create next app",
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const session = await getServerSession(authOptions)

  return (
    <html lang="en" data-theme="dark">
      <body className={inter.className}>
        <ClientProvider session={session}>
          <ToastProvider>
            <Nav />
            <main className="flex flex-col grow items-center justify-between h-full w-full">{children}</main>
            <Footer />
          </ToastProvider>
        </ClientProvider>
      </body>
    </html>
  )
}
