import "./globals.css"
import type { Metadata } from "next"
import { getServerSession } from "next-auth/next"
import { Inter } from "next/font/google"

import Provider from "@/app/context/client-provider"
import { authOptions } from "@/app/api/auth/[...nextauth]/route"
import Nav from "@/app/components/Nav"
import Footer from "@/app/components/Footer"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Instagram",
  description: "Generated by create next app",
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const session = await getServerSession(authOptions)

  return (
    <html lang="en" data-theme="dark">
      <body className={inter.className}>
        <Provider session={session}>
          <Nav />
          <main className="flex min-h-screen flex-col items-center justify-between p-24">
            {children}
          </main>
          <Footer />
        </Provider>
      </body>
    </html>
  )
}
